---
name: Deployment Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Check Style
        run: npm run eslint
      - name: Build Project
        run: npm run build
      - name: Run Unit Tests
        run: npm run test
      - name: Run E2E Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run e2e:test
          start: npm run start-prod
          wait-on: http://localhost:3000

...
        